?? status == 200
?? header content-type == application/json
?? js response.parsedBody.status == 200
?? js response.parsedBody.message == Ok.

@host=https://hitokoto.cn/api/restful/v1
/*
fn loginAndGetToken
*/
###
# @name loginAndGetToken
POST /auth/login
Content-Type: application/json

{
  "email": "{{HITOKOTO_EMAIL}}",
  "password": "{{HITOKOTO_PASSWORD}}"
}


@token={{loginAndGetToken.data[0].token}}

HTTP/1.1 200  - OK
connection: close
transfer-encoding: chunked
access-control-allow-headers: Authorization
access-control-allow-origin: *
cache-control: private, no-cache
content-encoding: gzip
content-type: application/json
date: Tue, 14 Oct 2025 02:24:58 GMT
ohc-upstream-trace: v1_Mainland_Trace_DogeCloud
server: nginx
strict-transport-security: max-age=39528000; includeSubDomains; preload
vary: Accept-Encoding
x-cache-lookup: Cache Miss, Hit From Upstream Cluster, Cache Miss
x-nws-log-uuid: 2269452584616352083
x-ratelimit-limit: 60
x-ratelimit-remaining: 59
###
# @ref loginAndGetToken
GET /user
Authorization: Bearer {{token}}
?? body data[0].id exists

HTTP/1.1 200  - OK
connection: close
transfer-encoding: chunked
access-control-allow-headers: Authorization
access-control-allow-origin: *
cache-control: private, no-cache
content-encoding: gzip
content-type: application/json
date: Tue, 14 Oct 2025 02:24:59 GMT
ohc-upstream-trace: v1_Mainland_Trace_DogeCloud
server: nginx
strict-transport-security: max-age=39528000; includeSubDomains; preload
vary: Accept-Encoding
x-cache-lookup: Cache Miss, Hit From Upstream Cluster, Cache Miss
x-nws-log-uuid: 9267902649174913980
x-ratelimit-limit: 60
x-ratelimit-remaining: 59
###
@uuid=49eff9ca-7145-4c5f-8e62-d3dca63537fa
# @name getHitokotoByUUID
# @ref loginAndGetToken
GET /hitokoto/{{uuid}}
Authorization: Bearer {{token}}

?? body data[0].hitokoto == 即使人生是一场悲剧，也应该笑着把人生演完。

HTTP/1.1 200  - OK
connection: close
transfer-encoding: chunked
access-control-allow-headers: Authorization
access-control-allow-origin: *
cache-control: private, no-cache
content-encoding: gzip
content-type: application/json
date: Tue, 14 Oct 2025 02:25:00 GMT
ohc-upstream-trace: v1_Mainland_Trace_DogeCloud
server: nginx
strict-transport-security: max-age=39528000; includeSubDomains; preload
vary: Accept-Encoding
x-cache-lookup: Cache Miss, Hit From Upstream Cluster, Cache Miss
x-nws-log-uuid: 957016223078579939
x-ratelimit-limit: 60
x-ratelimit-remaining: 58
###
# @ref getHitokotoByUUID
GET /hitokoto/{{uuid}}/score
Authorization: Bearer {{token}}

HTTP/1.1 200  - OK
connection: close
transfer-encoding: chunked
access-control-allow-headers: Authorization
access-control-allow-origin: *
cache-control: private, no-cache
content-encoding: gzip
content-type: application/json
date: Tue, 14 Oct 2025 02:25:01 GMT
ohc-upstream-trace: v1_Mainland_Trace_DogeCloud
server: nginx
strict-transport-security: max-age=39528000; includeSubDomains; preload
vary: Accept-Encoding
x-cache-lookup: Cache Miss, Hit From Upstream Cluster, Cache Miss
x-nws-log-uuid: 16471637996278212423
x-ratelimit-limit: 60
x-ratelimit-remaining: 57